---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-project-version-action
name: "🐍 Python Project Current Version"
description: "Returns the current version of a Python Project"
# Supports both pyproject.toml and setup.py project descriptions

inputs:
  # Mandatory
  PATH_PREFIX:
    description: "Directory location containing project code"
    type: string
    required: false

outputs:
  PYTHON_PROJECT_VERSION:
    description: "The current version declared for a Python project"
    value: ${{ steps.publish.outputs.python_project_version }}
  SOURCE:
    # yamllint disable-line rule:line-length
    description: "File used to source project metadata [pyproject.toml|setup.py]"
    value: ${{ steps.publish.outputs.python_project_version }}

runs:
  using: "composite"
  steps:
    - name: "Setup action/environment"
      shell: bash
      run: |
        # Setup action/environment
        # Handle path_prefix input consistently and when absent
        path_prefix="${{ inputs.PATH_PREFIX }}"
        if [ -z "$path_prefix" ]; then
          # Set current directory as path prefix
          path_prefix="."
        else
          # Strip any trailing slash in provided path
          path_prefix="${path_prefix%/}"
        fi
        # Verify is a valid directory path
        if [ ! -d "$path_prefix" ]; then
          echo "Error: invalid path/prefix to project directory ❌"; exit 1
        fi
        echo "path_prefix=$path_prefix" >> "$GITHUB_ENV"

    # yamllint disable-line rule:line-length
    - uses: lfreleng-actions/path-check-action@fb3d34249298b1165071de6a49ef24fc8423208c # v0.1.3
      id: setup-py
      with:
        path: "${{ env.path_prefix }}/setup-py"

    - name: "Use project version from setup.py"
      id: setup-py-version
      if: steps.setup-py.outputs.type == 'file'
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/file-grep-regex-action@e065e0d8edca06116113b652b077053c1f7056a0 # v0.1.2
      with:
        flags: "-oP -m1"
        # https://regex101.com/r/QKYHId/1
        regex: '(?<=version=")([^"]*)'
        filename: "${{ env.path_prefix }}/setup.py"

    # yamllint disable-line rule:line-length
    - uses: lfreleng-actions/path-check-action@fb3d34249298b1165071de6a49ef24fc8423208c # v0.1.3
      id: pyproject-toml
      with:
        path: "${{ env.path_prefix }}/pyproject.toml"

    - name: "Use project version from pyproject.toml"
      id: pyproject-toml-version
      if: steps.pyproject-toml.outputs.type == 'file'
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/file-grep-regex-action@e065e0d8edca06116113b652b077053c1f7056a0 # v0.1.2
      with:
        flags: "-oP -m1"
        # https://regex101.com/r/MWmRge/1
        regex: '(?<=^version = ")([^"]*)'
        filename: "${{ env.path_prefix }}/pyproject.toml"

    - name: "Error: Python project metadata NOT found"
      if: steps.pyproject-toml.outputs.type == 'invalid' &&
        steps.setup-py.outputs.type == 'invalid'
      shell: bash
      run: |
        # Error: Python project metadata NOT found
        echo "Error: neither pyproject.toml nor setup.py were found ❌"
        exit 1

    - name: "Return extracted values"
      id: publish
      shell: bash
      # yamllint disable rule:line-length
      run: |
        # Return extracted values

        # pyproject.toml is preferred source if both files exist
        if [ ${{ steps.pyproject-toml.outputs.type == 'file' }} ]; then
          echo "Using project version from source: pyproject.toml ✅"
          echo "source=pyproject.toml" >> "$GITHUB_ENV"
          echo "source=pyproject.toml" >> "$GITHUB_OUTPUT"
          PYTHON_PROJECT_VERSION="${{ steps.pyproject-toml-version.outputs.extracted_string}}"

        elif [ ${{ steps.setup-py.outputs.type == 'file' }} ]; then
          echo "Using project version from source: setup.py ⚠️"
          echo "Warning: consider migrating to modern PEP standards"
          echo "source=setup.py" >> "$GITHUB_ENV"
          echo "source=setup.py" >> "$GITHUB_OUTPUT"
          PYTHON_PROJECT_VERSION="${{ steps.setup-py-version.outputs.extracted_string}}"
        fi

        # Validate and output captured value
        if [ -z "$PYTHON_PROJECT_VERSION" ]; then
          echo "The project name extraction failed ❌"; exit 1
        fi
        echo "python_project_version: $PYTHON_PROJECT_VERSION ✅"
        echo "python_project_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_ENV"
        echo "python_project_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_OUTPUT"
