---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action 🧪'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Action Testing'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Perform setup prior to running test(s)
      - name: 'Checkout sample project repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'lfreleng-actions/test-python-project'
          path: 'test-python-project'

      - name: "Run Action: ${{ github.repository }}"
        uses: ./
        id: test
        with:
          path_prefix: 'test-python-project'

      - name: "Validate action output: ${{ github.repository }}"
        shell: bash
        run: |
          # Validate Action Output
          if [ "${{ steps.test.outputs.python_project_version }}" \
            = '0.0.1' ]; then
            echo "Action returned the expected results ✅"
          else
            echo 'Unexpected return value for: python_project_version ❌'
            echo "Returned: ${{ steps.test.outputs.python_project_version }}"
            echo 'Expected: 0.0.1'
            exit 1
          fi
